name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8, 3.9]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Set up Environment Variables
      env:
        NAME: ${{ secrets.NAME }}
        USER: ${{ secrets.USER }}
        PASSWORD: ${{ secrets.PASSWORD }}
        HOST: ${{ secrets.HOST }}
        PORT: ${{ secrets.PORT }}
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        ALLOWED_HOSTS: ${{ secrets.ALLOWED_HOSTS }}
    - name: Create secrets.json
      run: echo '${{ secrets.SECRETS }}' > hanwooplz_project/hanwooplz_project/secrets.json
    - name: Run Tests
      run: |
        cd hanwooplz_project
        export NAME=$NAME
        export USER=$USER
        export PASSWORD=$PASSWORD
        export HOST=$HOST
        export PORT=$PORT
        exprot SECRET_KEY=$SECRET_KEY
        exprot ALLOWED_HOSTS=$ALLOWED_HOSTS
        python manage.py test
