name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8, 3.9]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Get secrets and create secrets.json
      run: |
        echo "{" > hanwooplz_project/hanwooplz_project/secrets.json
        echo "  \"NAME\": \"${{ secrets.NAME }}\"," >> hanwooplz_project/hanwooplz_project/secrets.json
        echo "  \"USER\": \"${{ secrets.USER }}\"," >> hanwooplz_project/hanwooplz_project/secrets.json
        echo "  \"PASSWORD\": \"${{ secrets.PASSWORD }}\"," >> hanwooplz_project/hanwooplz_project/secrets.json
        echo "  \"HOST\": \"${{ secrets.HOST }}\"," >> hanwooplz_project/hanwooplz_project/secrets.json
        echo "  \"PORT\": \"${{ secrets.PORT }}\"," >> hanwooplz_project/hanwooplz_project/secrets.json
        echo "  \"SECRET_KEY\": \"${{ secrets.SECRET_KEY }}\"," >> hanwooplz_project/hanwooplz_project/secrets.json
        echo "  \"ALLOWED_HOSTS\": \"${{ secrets.ALLOWED_HOSTS }}\"" >> hanwooplz_project/hanwooplz_project/secrets.json
        echo "}" >> hanwooplz_project/hanwooplz_project/secrets.json
        cat hanwooplz_project/hanwooplz_project/secrets.json  # Verify the content of secrets.json
    - name: Run Tests
      run: |
        cd hanwooplz_project
        python manage.py test
