name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8, 3.9]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Clear secrets.json
      run: |
        echo "" > hanwooplz_project/hanwooplz_project/secrets.json
        cat hanwooplz_project/hanwooplz_project/secrets.json  # secrets.json 파일 내용 확인
    - name: Get secrets
      run: |
        echo "${{ secrets.SECRETS }}" > hanwooplz_project/hanwooplz_project/secrets.json
        cat hanwooplz_project/hanwooplz_project/secrets.json  # secrets.json 파일 내용 확인
    - name: Run Tests
      env:
        NAME: ${{ secrets.NAME }}
        USER: ${{ secrets.USER }}
        PASSWORD: ${{ secrets.PASSWORD }}
        HOST: ${{ secrets.HOST }}
        PORT: ${{ secrets.PORT }}
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        ALLOWED_HOSTS: ${{ secrets.ALLOWED_HOSTS }}
      run: |
        cd hanwooplz_project
        python manage.py test
